### ISSUE TITLE
Question about ARM irq handler

### ISSUE THREAD

**Issue by garthlei** [jcsaezal/pmctrack#18]
Hi,

I have a question about the ARM interrupt handler. The ARM/ARM64 kernel module registers a handler for overflow interrupts, but the ARM PMU perf driver also registers a handler. Since the interrupts are not configured as shared, do users still have to modify the kernel, or disable the kernel perf event driver when building the kernel, to make this work?

**Comment by jcsaezal** [comment]
Hi @garthlei,

That's a really good question.

ARM and ARM64 kernel modules are *legacy* PMCTrack modules. Starting with PMCTrack v2.0, PMCTrack can be used on top of vanilla Linux kernels and using perf as a backend to access performance monitoring counters (`mchw_perf.ko` module). That new kernel module does not register a handler for overflow interrupts, as it relies on installing perf events's overflow callbacks. 

The reason why ARM/ARM64 kernel modules still exist in PMCTrack is to allow our tool to work on systems for which no recent versions of the Linux kernel (>=5.9.x) are officially supported. For a long time, this has been the case of a bunch of ARM-based boards featuring big.LITTLE processors, such as the Odroid-XU4. We have not tested yet the perf-based kernel module with the new Odroid kernel (based on Linux v6.1), which was recently released by the board's vendor. Keep in mind, though, that so far we have only experimented with the ARM/ARM64 modules on ARM embedded boards. Any initiative/help to test and port PMCTrack on ARM server systems would be greatly appreciated.

Lastly, I'd like to highlight that we still intensively use other PMCTrack legacy backends for research, such as `mchw_intel_core.ko` or   `mchw_amd.ko`. PMCTrack's API to access performance counters is much more versatile than perf-event's API. These legacy backends "steal" the overflow interrupt from perf events, when the associated kernel module is inserted in the kernel. This does not require patching the kernel, as we use an ftrace hook for that purpose. I believe that a similar thing can be done with PMC overflow IRQ handlers on ARM, but we could not test that on our ARM-based systems yet due to the fact that ftrace is not fully supported in older kernels. In the future we will try to add this "stealing" feature to ARM/ARM64 modules, but we'll need to purchase a new ARM system for this purpose.

I hope this helps!

**Comment by garthlei** [comment]
Thank you!
