### ISSUE TITLE
PMCTrack for Odroid Smart Power

### ISSUE THREAD

**Issue by anwesha94** [jcsaezal/pmctrack#3]
Hi,
Is there any documentation of how to get energy/power samples periodically from an Odroid Smart Power2 board using pmctrack?
Thank you,
Anwesha

**Comment by jcsaezal** [comment]
Hi Anwesha,

Currently, PMCTrack only allows the gathering of energy/power samples from an Odroid Smart Power (v1.0). Unfortunately, the USB kernel-level driver included in our tool is not compatible with the Odroid Smart Power2 device; there are substantial differences between Odroid Smart Power v1 and v2. 

Kind regards,

Juan Carlos

**Comment by anwesha94** [comment]
Hi, Is there any plan to include smart power2 with pmctrack. ISmart Power is no more sold by odroid. pmctrack seemed to be a good solution in recording the energy stats. Please let me know.
Thank you.

**Comment by jcsaezal** [comment]
Hi Anwesha,

At this point none of the project contributors has access to a Smart Power 2, so we do not have plans to add support for that device shortly. In case someone wants to contribute to the project by including support for Smart Power 2 I will let you know.

Regards

**Comment by anwesha94** [comment]
Hi,
This is in different context. Is there a patch for linux kernel 4.9.y?

**Comment by jcsaezal** [comment]
Hi Anwesha,

Could you please open another issue regarding this matter?

Thanks

**Comment by sirfonzie** [comment]
Hi,
How does the PMCTrack obtain the power reading from the Odroid Smart Power (v1.0)?
Is it via the pmctrack-gui?

As best as I know, the smart power data is only fed via usb to a software on PC.
Thus how would PMCTrack detect it on the ODROID-XU3?

-Fauzi

**Comment by jcsaezal** [comment]
Hi,

PMCTrack is equipped with a [kernel-level USB driver](https://github.com/jcsaezal/pmctrack/blob/master/src/modules/pmcs/smart_power_driver.c) for the Odroid Smart Power device. In order to use that driver, whose functionality is exposed via a PMCTrack monitoring module, you must add the USB device to the blacklist of the `usbhid` driver so that PMCTrack's driver can handle the Smart Power Device. To make this happen, you must use the following kernel boot option on the Odroid board:

```
usbhid.quirks=0x04d8:0x003f:0x0004
```

That option must be included in the bootargs variable inside the `boot.ini` U-boot's config file (found in the board's boot partition).


Once the Linux kernel boots (with that option), you must connect the Odroid Smart Power via USB to the Odroid board (rather than to an external PC). As soon as you load the PMCTrack kernel module (as explained in the [tutorial](https://pmctrack.dacya.ucm.es/install/pmctrack-on-odroid-xu3-4/)), the driver built in PMCTrack should start handling the device. If the file `/dev/usb/spower0` was created, then it means that everything is going fine.

Finally, to get energy and power measurements from the Smart Power Device via the `pmctrack` command-line tool, you should enable the ``Odroid Smart Power`` monitoring module that comes with PMCTrack. Note that it is not enabled by default:

```
$ cat /proc/pmc/mm_manager
[*] 0 - This is just a proof of concept
[ ] 1 - IPC sampling SF estimation module
[ ] 2 - Odroid Smart Power
```

To enable it:

```
$ echo activate 2 > /proc/pmc/mm_manager
$ cat /proc/pmc/mm_manager
[ ] 0 - This is just a proof of concept
[ ] 1 - IPC sampling SF estimation module
[*] 2 - Odroid Smart Power
```

This driver exposes 3 virtual counters to user-space tools:

```
$ pmc-events -V
[Virtual counters]
power_mw
current_ma
energy_uj  
```

... and they can be used via the `-V` switch of `pmctrack` to retrieve information from the Odroid Smart Power. You can even gather information from performance counters and energy measurements at the same time (in a fully coordinated fashion) as follows:

```
$ pmctrack -b 4 -c llc_misses,instr -V power_mw,energy_uj -T 0.5  ./hmmer06
[Event-to-counter mappings]
pmc1=llc_misses
pmc2=instr
virt0=power_mw
virt2=energy_uj
[Event counts]
nsample    pid      event          pmc1          pmc2    virt0         virt2
      1  13594       tick        537850    1747080239     4431       2215900
      2  13594       tick        667758    2050841122     6429       3214900
      3  13594       tick       1218564    2062162739     6764       3382200
      4  13594       tick       2164923    2038336610     6854       3427400
      5  13594       tick       1674625    2065411454     6936       3468400
      6  13594       tick       1862785    2059762222     6944       3472300
      7  13594       tick       1618331    2065219211     6942       3471300
      8  13594       tick       2384766    2032207379     7004       3502400
.....
```

Because the support for the Odroid Smart Power was created as part of the final degree project of two of my students, you can find more information in Section 2.3 of the [report they wrote](http://eprints.ucm.es/38726/1/Memoria.pdf). It is in Spanish, but perhaps Google Translate can help you out with that  :-)

Well, I hope you find that information useful.

--Juan Carlos

**Comment by anwesha94** [comment]
@sirfonzie 
Hi, I was wondering were you able to record power and energy from the odroidxu3 board?
Thanks.

**Comment by sirfonzie** [comment]
I did get power measurement but not using the smart power. I used the on-board XU3 current measurement to get the readings then calculate the power.

You can use the script (obtained from the link below) to get the temperature, current, voltage, power, etc from the XU3 on-board sensors.

https://github.com/sagark/odroid-xu3-bench

**Comment by anwesha94** [comment]
But the current odroid boards do not come with INA231a sensors. Are you using old odroidxu3 board?
I am sorry , I think this is not particularly relevant to pmctrack.

**Comment by jcsaezal** [comment]
Hi,

We just [added the support](https://github.com/jcsaezal/pmctrack/commit/54c0b4dfc9629e7d0e876756d21d6478b877f2a0) to monitor power consumption with Odroid Smart Power 2. Essentially we created a new monitoring module that exports three virtual counters (`power_mw`, `current_ma` and `energy_uj `) just like the "old" monitoring module for Odroid Smart Power v1 (recall that it is a very different hardware device).

For a better experience in using PMCTrack's support for Odroid Smart Power 2, users are strongly encouraged to increase the sampling period of the device from 1 second (default)  to 100ms. 
This entails upgrading Odroid Smart Power 2's firmware using a modified version. The instructions on how to update the firmware can be found at the [manufacturer's site](https://wiki.odroid.com/accessory/power_supply_battery/smartpower2#platformio). Note also that the necessary changes in the firmware's source code are already available in [this repository](https://github.com/Dres0109/smartpower2/tree/arduino/smartpower2), so you may clone this repository instead of the one mentioned in the [manufacturer's tutorial](https://wiki.odroid.com/accessory/power_supply_battery/smartpower2#platformio).

--Juan Carlos
