### ISSUE TITLE
patch for odroid xu4 linux kernel 4.9.y 

### ISSUE THREAD

**Issue by anwesha94** [jcsaezal/pmctrack#4]
Is there a patch of linux kernel 4.9.y for odroid xu4?

**Comment by jcsaezal** [comment]
We will try to include support for [that kernel version](https://github.com/hardkernel/linux/tree/odroidxu4-4.9.y) in the next major PMCTrack release. 

--Juan Carlos

**Comment by jcsaezal** [comment]
Two kernel patches (for v4.14 and v4.9 of the odroid kernels) were added to the [repository](https://github.com/jcsaezal/pmctrack/tree/master/src/kernel-patches). Nevertheless, PMCTrack now works without patching the odroid kernel and thanks to the new version of the perf backend, which now supports the odroid board. So, due to that new support, it is likely that no further kernel patches are released for the odroid-xu3/4 board. 

--Juan Carlos
